harnessApiVersion: '1.0'
type: CANARY
concurrencyStrategy: INFRA
envName: QA
failureStrategies:
- executionScope: WORKFLOW
  failureTypes:
  - APPLICATION_ERROR
  repairActionCode: ROLLBACK_WORKFLOW
  retryCount: 0
notificationRules:
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupNames:
  - Account Administrator
phases:
- type: KUBERNETES
  computeProviderName: Kubernetes Cluster Diego-GKE
  daemonSet: false
  infraDefinitionName: Diego-GKE-DEV
  name: Canary
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    steps:
    - type: K8S_CANARY_DEPLOY
      name: Canary Deployment
      properties:
        instanceUnitType: PERCENTAGE
        instances: '50'
        stateTimeoutInMinutes: 10
        templateUuid: null
        templateVariables: null
        templateVersion: null
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Verify
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    steps:
    - type: K8S_DELETE
      name: Canary Delete
      properties:
        instanceUnitType: COUNT
        resources: ${k8s.canaryWorkload}
    stepsInParallel: false
  provisionNodes: false
  serviceName: diego-java-springboot-service
  statefulSet: false
  templateExpressions:
  - expression: ${InfraDefinition_Kubernetes}
    fieldName: infraDefinitionId
    metadata:
    - name: artifactType
      value: DOCKER
    - name: entityType
      value: INFRASTRUCTURE_DEFINITION
rollbackPhases:
- type: KUBERNETES
  daemonSet: false
  infraDefinitionName: Diego-GKE-DEV
  name: Rollback Canary
  phaseNameForRollback: Canary
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    phaseStepNameForRollback: Deploy
    statusForRollback: SUCCESS
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    phaseStepNameForRollback: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: diego-java-springboot-service
  statefulSet: false
  templateExpressions:
  - expression: ${InfraDefinition_Kubernetes}
    fieldName: infraDefinitionId
    metadata:
    - name: artifactType
      value: DOCKER
    - name: entityType
      value: INFRASTRUCTURE_DEFINITION
templateExpressions:
- expression: ${Environment}
  fieldName: envId
  metadata:
  - name: relatedField
  - name: entityType
    value: ENVIRONMENT
templatized: true
userVariables:
- type: ENTITY
  description: Variable for Environment entity
  fixed: false
  mandatory: true
  name: Environment
- type: ENTITY
  description: Variable for Infrastructure Definition entity in Rollback Canary
  fixed: false
  mandatory: true
  name: InfraDefinition_Kubernetes
