apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
spec:
  replicas: {{int .Values.replicas}}
  selector:
    matchLabels:
      app: {{.Values.name}}
      tier: {{.Values.tier}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
        tier: {{.Values.tier}}
    spec:
      containers:
      - name: {{.Values.container}}
        image: {{.Values.image}}
        resources:
          requests:
            cpu: {{.Values.cpu}}
            memory: {{.Values.memory}}
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: {{.Values.servicePort}}