apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}
spec:
  type: {{.Values.serviceType}}
  ports:
  - port: {{.Values.servicePort}}
    targetPort: {{.Values.serviceTargetPort}}
    protocol: {{.Values.protocol}}
  selector:
    app: {{.Values.name}}
{{- if .Values.createIngress}}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: diego-ingress
spec:
  backend:
    serviceName: {{.Values.name}}
    servicePort: {{.Values.serviceTargetPort}}
{{- end}}